#pragma config(Sensor, S1,     ntouch,         sensorTouch)
#pragma config(Sensor, S2,     nlight,         sensorLightActive)
#pragma config(Sensor, S3,     ntouch,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward()
{
motor[motorB] = 50;
motor[motorC] = 50;
wait1Msec(1000);
}
void left()
{
motor[motorB] = 0;
motor[motorC] = 50;
wait1Msec(720);
}
void right()
{
motor[motorB] = 50;
motor[motorC] = 0;
wait1Msec(720);
}
void backwards()
{
motor[motorB] = -50;
motor[motorC] = -50;
wait1Msec(2000);
}
void wait()
{
motor[motorB] = 0;
motor[motorC] = 0;
wait1Msec(1000);
}

task main()
{
while(SensorValue[ntouch] == 0)
	{
	forward();
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(0350);
	wait();
	left();
	wait();
	forward();
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(0900);
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(0700);
	wait();
	left();//call the left subroutine
	wait();
	forward();
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(1000);
	wait();

	if (SensorValue[nlight] < 100)
	{
	backwards();
	}
	wait();
	left();//call the left subroutine
	wait();
	forward();
	forward();
	motor[motorB] = 50;
	motor[motorC] = 50;
	wait1Msec(0500);
	wait();
	left();
	wait();
	forward();
	forward();

	if (SensorValue[nlight] < 100)
	{
	break;
	}
	}
motor[motorB] = 0;
motor[motorC] = 0;
wait1Msec(7000);
}
